a = input('enter a: ')
b = input('enter b: ')
sum = int(a) + int(b)
print('addition of the inputed numbers are: ')
print(sum)
sum = int(a) - int(b)
print('substraction of the inputed numbers are: ')
print(sum)
sum = int(a) * int(b)
print('multiplication of the inputed numbers are: ')
print(sum)
sum = float(a)/ float(b)
print('division of the inputed numbers are: ')
print(sum)

