number = input('enter 1 number')
number1 = input('enter second number')
addition = int(number)
addition1 = int(number1)
print("addition is ",+addition + addition1 )
print("substaction is ",+addition - addition1 )
print("multiplication is", +addition*addition)
print("division ",+addition / addition1 )
print("exponent is", +addition ** addition1)
print("modulus is" ,+addition% addition1)
